#!/bin/bash

TZ="Asia/Seoul"

date_kst() {
  TZ=$TZ date $@
}

format_offset() {
  local offset=$1
  printf "%05d.webp" "$offset"
}

current_year=$(date_kst +%Y)
offset=$((10#$(date_kst +"%j")))
last_day_of_leap_year=366

if [ $offset -eq $last_day_of_leap_year ]; then
  offset=$(($offset - 1))
fi

day_image_offset=$((offset * 2 - 1))
night_image_offset=$((offset * 2 - 2))

day_image_name=$(format_offset $day_image_offset)
night_image_name=$(format_offset $night_image_offset)

current_time=$((10#$(date_kst +"%H")))

if [ $current_time -ge 12 ]; then
  image_name=$day_image_name
else
  image_name=$night_image_name
fi

echo "Update on: $(date_kst)"
echo "Current image is now: $image_name"

alt=earth-go-round

sed -i "s/\[$alt\](.*)/\[$alt\](images\/$image_name)/g" README.md
