#!/bin/bash

START_POINT=3
TZ="Asia/Seoul"

date_kst() {
  TZ=$TZ date $@
}

calc_offset() {
  local nth_day=$1
  if [ $nth_day -lt $START_POINT ]; then
    echo $((2 * ($nth_day + 362)))
   else
    echo $((2 * ($nth_day - 3)))
  fi
}

format_offset() {
  local offset=$1
  printf "%05d.webp" "$offset"
}

current_year=$(date_kst +%Y)
nth_day=$((10#$(date_kst +"%j")))
last_day_of_leap_year=366

if [ $nth_day -eq $last_day_of_leap_year ]; then
  nth_day=$(($nth_day - 1))
fi

night_image_offset=$(calc_offset $nth_day)
day_image_offset=$(($(calc_offset $nth_day) + 1))

night_image_name=$(format_offset $night_image_offset)
day_image_name=$(format_offset $day_image_offset)

current_time=$((10#$(date_kst +"%H")))

if [ $current_time -ge 12 ]; then
  image_name=$day_image_name
else
  image_name=$night_image_name
fi

echo "Update on: $(date_kst)"
echo "Current image is now: $image_name"

alt=earth-go-round

sed -i "s/\[$alt\](.*)/\[$alt\](images\/$image_name)/g" README.md
