name: Update the image based on the current date

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3-15/12 * * *"

permissions:
  contents: write

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make `update` executable
        run: chmod +x ./update

      - name: Update image
        run: ./update

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & Push
        run: |
          git commit -am "docs: update the earth-go-round image"
          git push
