name: Update the image based on the current date

on:
  schedule:
    - cron: "0 3-15/12 * * *"

jobs:
  update-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Make `update` executable
        run: chmod +x ./update

      - name: Update image
        run: ./update

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & Push
        run: |
          git commit -am "chore: update image"
          git push
